### ISSUE TITLE
show 方法的隐藏时间可以改成可选吗？目前就自定义视图是可选的

### ISSUE THREAD

**Issue by baiyidjp** [iAmMccc/MCBubble#1]

**Comment by intsig171** [comment]
你是希望可以设置为nil，不主动隐藏气泡么？

**Comment by intsig171** [comment]
最新版本 V0.0.4，已经支持可选。您可以使用nil填充隐藏时间，即：不自动隐藏。

**Comment by baiyidjp** [comment]
> 最新版本 V0.0.4，已经支持可选。您可以使用nil填充隐藏时间，即：不自动隐藏。

好的，谢谢大佬
