### ISSUE TITLE
可以加上气泡区域外点击穿透吗？

### ISSUE THREAD

**Issue by callmewenxi** [iAmMccc/MCBubble#4]
可以加上气泡区域外点击事件穿透吗？有些场景需要用到

**Comment by intsig171** [comment]
现在气泡是通过计算目标控件相对于屏幕的位置，现在在屏幕上的。 也就是说 如果滑动页面，气泡是不会随着页面滑动的。为了防止这种情况的发生，特意盖住了整个屏幕，防止穿透。  为了实现你的需求，需要改变这个逻辑，将气泡跟目标绑定（add到目标上）。 我需要点时间思考一下。 你可以加我的QQ详细了解。QQ在另外一个仓库SmartCodable的reademe中有。
