### ISSUE TITLE
提个问题

### ISSUE THREAD

**Issue by kkkkkkkkNight** [iAmMccc/MCBubble#5]
let bubble = BTBubble()
        // 入场 无
        bubble.entranceAnimation = .none
        // 特效 弹性
        bubble.actionAnimation = .bounce(2)
        // 离场 无
        bubble.exitAnimation = .none
        bubble.show()
        
        为什么我设置了以上效果后，自定义View的点击事件就消失了。但我不设置效果，就没问题

**Comment by intsig171** [comment]
你的意思是在一个自定义的view上添加bubble，弹出bubble之后自定义的view不再响应事件？

**Comment by intsig171** [comment]
![image](https://github.com/intsig171/BTBubble/assets/87351449/7be5b922-d970-476a-9433-8452172bebe6)
我这里尝试的是正常的。 建议提供一个可复现的demo。
